/* ============================================================
   site-data.js — content for the personal-site UI kit.
   Bilingual (EN / 中文). Structured around the three career
   parts from Zhao Wang's interview deck. Content drawn from the
   CV (zhao_wang_cv_Academic.qmd) and Presentation_ZH.html.

   Bilingual fields are { en, zh }; plain strings are shared.
   Read them with the tx(value, lang) helper. Exposed as window.SITE.
   ============================================================ */
window.SITE = {
  ui: {
    nav: {
      about:        { en: "About",        zh: "简介" },
      work:         { en: "Career",       zh: "工作经历" },
      talks:        { en: "Talks",        zh: "演讲" },
      publications: { en: "Publications", zh: "论文发表" },
      contact:      { en: "Get in touch", zh: "联系我" },
    },
    hero: {
      status:  { en: "Open to collaboration", zh: "欢迎合作交流" },
      seeWork: { en: "See my work",            zh: "查看工作经历" },
      scholar: { en: "Scholar",                zh: "学术主页" },
    },
    sections: {
      aboutEyebrow:  "cat about.md",
      aboutTitle:    { en: "Research that ships as software", zh: "让研究落地为可用的软件" },
      workEyebrow:   "ls -la ~/career",
      workTitle:     { en: "Ten years across structures, infrastructure & transport AI", zh: "十年：从结构工程到基础设施数据与交通AI" },
      workIntro:     { en: "From civil & structural engineering, to national infrastructure data and AI, to open-source transport-network science.", zh: "从土木与结构工程，到国家级基础设施数据与人工智能，再到开源交通网络科学。" },
      talksEyebrow:  { en: "Talks & demos",  zh: "演讲与演示" },
      talksTitle:    { en: "Watch the research in action", zh: "研究成果实录" },
      talksIntro:    { en: "How satellite imagery and machine learning can map road conditions where survey data doesn't exist.", zh: "如何用卫星影像与机器学习，在缺乏实地调查的地区评估路况。" },
      pubsEyebrow:   "grep -ri 'paper' ./publications",
      pubsTitle:     { en: "Publications", zh: "论文发表" },
      pubsIntro:     { en: "19 peer-reviewed journal papers and selected conference papers. Full citations on Google Scholar.", zh: "19 篇同行评审期刊论文及代表性会议论文，完整引用见 Google Scholar。" },
      eduTitle:      { en: "Education", zh: "教育背景" },
      rolesLabel:    { en: "Roles", zh: "职位" },
    },
    pubs: {
      all:        { en: "All",        zh: "全部" },
      journal:    { en: "Journal",    zh: "期刊" },
      conference: { en: "Conference", zh: "会议" },
      best:       { en: "Best Paper", zh: "最佳论文" },
      doi:        { en: "DOI",        zh: "DOI" },
      find:       { en: "Find paper", zh: "查找论文" },
    },
    contact: {
      title: { en: "Let's build something useful", zh: "一起做点真正有用的东西" },
      body:  { en: "Open to research collaborations, tool development and consulting on transport data, GIS and machine learning.", zh: "在交通数据、GIS 与机器学习方向，欢迎科研合作、工具开发与技术咨询。" },
      back:  { en: "Back to top", zh: "回到顶部" },
    },
  },

  person: {
    name: "Zhao Wang",
    nameZh: "王曌",
    role:        { en: "Transport Data Scientist & GIS Researcher", zh: "交通数据科学家 & GIS 研究员" },
    affiliation: { en: "Institute for Transport Studies · University of Leeds", zh: "英国利兹大学 · 交通研究所" },
    tagline:     { en: "I build open-source tools that turn messy spatial data into route networks planners can act on — across cycling, road safety and resilient infrastructure.", zh: "我做开源工具，把零散杂乱的空间数据，变成规划者能直接上手的交通路网——覆盖骑行出行、道路安全与韧性基础设施。" },
    email: "wangzhao0217@gmail.com",
    location: { en: "Leeds, UK", zh: "英国 · 利兹" },
    links: {
      github: "https://github.com/wangzhao0217",
      scholar: "https://scholar.google.com/scholar?q=Zhao+Wang+transport+network+rubberised+concrete",
      linkedin: "https://www.linkedin.com/feed/",
    },
  },

  stats: [
    { value: "19",   label: { en: "Journal articles",     zh: "期刊论文" },   sublabel: { en: "peer-reviewed",     zh: "同行评审" } },
    { value: "6",    label: { en: "Open-source packages", zh: "开源软件包" }, sublabel: { en: "R · Python", zh: "R · Python" } },
    { value: "5",    label: { en: "Conference papers",    zh: "会议论文" },   sublabel: { en: "incl. Best Paper",  zh: "含最佳论文奖" } },
    { value: "10yr", label: { en: "Research & practice",  zh: "科研与实践" }, sublabel: { en: "UK · EU",           zh: "英国 · 欧盟" } },
  ],

  about: [
    { en: "I'm a transport data scientist with a Ph.D. in Civil & Structural Engineering and over six years of experience in geospatial analysis, network modelling and spatial database design.",
      zh: "我是一名交通数据科学家，拥有土木与结构工程博士学位，在空间数据分析、网络建模与空间数据库设计方面有六年以上经验。" },
    { en: "My work bridges academic research and national infrastructure practice — from open-source R, Python and Rust packages adopted by UK government transport agencies, to machine learning for infrastructure condition assessment.",
      zh: "我的工作横跨学术研究与国家级基础设施实践：既有被英国政府交通机构采用的 R、Python、Rust 开源软件包，也有用于基础设施状态评估的机器学习。" },
  ],

  // ---- Three career parts (mirrors the interview deck) ----
  parts: [
    {
      num: "PART 1",
      title:  { en: "Civil & Structural Engineering", zh: "土木与结构工程" },
      period: "2015 – 2022",
      roles: [
        { en: "Ph.D., Civil & Structural Engineering — University of Sheffield", zh: "土木与结构工程博士 — 英国谢菲尔德大学" },
        { en: "Research Associate — Nuclear AMRC, University of Sheffield",       zh: "研究员 — 英国谢菲尔德大学核先进制造研究中心 Nuclear AMRC" },
        { en: "Structural Engineer — Waterman Group",                            zh: "结构工程师 — 英国 Waterman Group" },
      ],
      blurb: { en: "Material constitutive modelling, large-scale nonlinear FE dynamics and special-structure assessment.", zh: "材料本构建模、大型非线性有限元动力分析与特种结构评估。" },
      projects: [
        { title: { en: "Concrete constitutive modelling & FE simulation", zh: "混凝土本构与有限元仿真" },
          image: null, motif: "fea",
          blurb: { en: "Constitutive models for high-performance & rubberised concrete; 3D nonlinear FE dynamics for a 9 m drop and near-field blast on nuclear decommissioning containers (DCC).", zh: "面向高性能混凝土与橡胶混凝土的本构模型；针对核退役容器（DCC）9 米跌落与近场爆炸的三维非线性有限元动力仿真。" },
          details: { highlights: [
            { en: "Developed constitutive models for high-performance & rubberised concrete validated against experiments.", zh: "建立高性能混凝土与橡胶混凝土的本构模型，并通过试验验证。" },
            { en: "Ran 3D nonlinear FE dynamic simulations of a 9 m drop and near-field blast on nuclear decommissioning containers.", zh: "完成核退役容器 9 米跌落与近场爆炸的三维非线性有限元动力仿真。" },
            { en: "Linked material modelling to structural safety cases for high-consequence assets.", zh: "将材料建模与高风险结构的安全论证打通。" },
          ] },
          tags: [{ tone: "kraft", label: { en: "FEA", zh: "有限元" } }, { tone: "slate", label: { en: "Concrete", zh: "混凝土" } }],
          links: [],
          papers: [
            { emoji: "🧱",
              title: { en: "Fibre length effects in recycled-steel-fibre concrete", zh: "回收钢纤维混凝土的纤维长度效应" },
              venue: { en: "Construction and Building Materials · 2024", zh: "建筑与建筑材料 · 2024" },
              year: "2024", doi: "10.1016/j.conbuildmat.2024.134890", role: "first",
              contribution: { en: "Tested 7 recycled-tyre fibre lengths; residual flexural strength rises near-linearly up to an optimal 21 mm.", zh: "测试 7 种回收轮胎钢纤维长度，残余抗弯强度随长度近似线性提升，21 mm 时最优。" },
              metric: { en: "21 mm optimum", zh: "21 mm 最优" },
              img: "assets/papers/sfrc-fibre-length-1.jpg",
              imgAlt: { en: "Load-deflection curves: experiment vs FE model across fibre lengths", zh: "荷载-挠度曲线：不同纤维长度下试验与有限元结果对比" } },
            { emoji: "🛞",
              title: { en: "Axial behaviour of FRP-confined rubberised concrete", zh: "FRP 约束橡胶混凝土的轴向力学行为" },
              venue: { en: "Constr. Build. Mater. · 2020", zh: "Constr. Build. Mater. · 2020" },
              year: "2020", doi: "10.1016/j.conbuildmat.2020.121023", role: "first",
              contribution: { en: "96 compression tests show FRP confinement restores strength and pushes rubberised concrete to 5.7% ultimate axial strain.", zh: "96 组轴压试验表明，FRP 约束能恢复强度，并将橡胶混凝土的极限轴向应变提升至 5.7%。" },
              metric: { en: "5.7% axial strain", zh: "5.7% 轴向应变" },
              img: "assets/papers/frp-axial-1.jpg",
              imgAlt: { en: "Tensile-rupture failure modes of FRP-confined concrete cylinders (Aramid vs Carbon, 0% vs 60% rubber)", zh: "FRP 约束混凝土圆柱试件的拉断破坏模式（芳纶与碳纤维，0% 与 60% 橡胶掺量）" } },
            { emoji: "🧱",
              title: { en: "Tensile stress-strain of rubberised concrete from flexural tests", zh: "由弯曲试验反演橡胶混凝土的拉伸应力-应变特性" },
              venue: { en: "Construction and Building Materials · 2020", zh: "Construction and Building Materials · 2020" },
              year: "2020", doi: "10.1016/j.conbuildmat.2019.117591", role: "first",
              contribution: { en: "Inverse-FEA tensile model cuts flexural-load error to 3% versus 32% for Model Code 2010.", zh: "逆向有限元拉伸模型将抗弯荷载误差降至 3%，而 Model Code 2010 的误差为 32%。" },
              metric: { en: "3% vs 32% error", zh: "误差 3% 对 32%" },
              img: "assets/papers/rubberised-tensile-1.jpg",
              imgAlt: { en: "Predicted vs experimental load-deflection curves for plain and rubberised concrete (R0/R30/R60)", zh: "普通与橡胶混凝土（R0/R30/R60）荷载-挠度曲线的预测值与实测值对比" } },
            { emoji: "🧱",
              title: { en: "Shear Behavior Model for FRP-Confined and Unconfined Rubberized Concrete", zh: "FRP 约束与无约束橡胶混凝土的抗剪行为模型" },
              venue: { en: "J. Composites for Construction (ASCE)", zh: "J. Composites for Construction (ASCE)" },
              year: "2019", doi: "10.1061/(ASCE)CC.1943-5614.0000962", role: "first",
              contribution: { en: "First fixed-angle softened-truss shear model for rubberized concrete; predictions match 18 FRP-confined tests (ratio 1.02).", zh: "首个面向橡胶混凝土的定角软化桁架抗剪模型，与 18 个 FRP 约束试件吻合（实测/预测 1.02）。" },
              metric: { en: "test/pred 1.02", zh: "实测/预测 1.02" },
              img: "assets/papers/rubberised-shear-1.jpg",
              imgAlt: { en: "Predicted vs experimental shear stress-strain and load-deflection curves for confined rubberized concrete at three a/d ratios", zh: "约束橡胶混凝土在三种剪跨比下，剪应力-应变与荷载-挠度曲线的预测值与实测值对比" } },
            { emoji: "🧱",
              title: { en: "Post-cracking Tensile Behaviour of Blended Steel-Fibre Concrete", zh: "混杂钢纤维混凝土的开裂后拉伸行为" },
              venue: { en: "Structural Concrete", zh: "Structural Concrete" },
              year: "2018", doi: "10.1002/suco.201800100", role: "co",
              contribution: { en: "Showed RILEM overestimates peak flexural load by up to 72%, then proposed an accurate trilinear tensile model.", zh: "发现 RILEM 将峰值抗弯荷载高估达 72%，进而提出更准确的三折线拉伸本构模型。" },
              metric: { en: "up to 72% overestimate", zh: "最高高估 72%" },
              img: "assets/papers/blended-sfrc-tensile-1.jpg",
              imgAlt: { en: "Measured vs RILEM, MC2010 and inverse-analysis load-deflection curves for 10 SFRC mixes", zh: "10 种钢纤维混凝土配合比：实测与 RILEM、MC2010 及逆向分析荷载-挠度曲线对比" } },
          ] },
        { title: { en: "Structural assessment & AI crack detection", zh: "结构评估与 AI 裂缝检测" },
          image: null, motif: "crack",
          blurb: { en: "CS454 CAT-2 assessment of Greys Bridge; Drax FGD steel-structure stability; AI image-based concrete crack monitoring.", zh: "Greys 大桥 CS454 CAT-2 评估、Drax 电厂 FGD 钢结构稳定性分析，以及基于图像 AI 的混凝土裂缝监测。" },
          details: { highlights: [
            { en: "Carried out a CS454 CAT-2 structural assessment of Greys Bridge.", zh: "完成 Greys 大桥的 CS454 CAT-2 结构评估。" },
            { en: "Assessed Drax FGD steel-structure stability under operational loads.", zh: "评估 Drax 电厂 FGD 钢结构在运行荷载下的稳定性。" },
            { en: "Prototyped image-based AI for automated concrete crack detection & monitoring.", zh: "搭建基于图像 AI 的混凝土裂缝自动检测与监测原型。" },
          ] },
          tags: [{ tone: "slate", label: { en: "Assessment", zh: "结构评估" } }, { tone: "heather", label: "AI" }],
          links: [],
          papers: [
            { emoji: "🧩",
              title: { en: "Crack opening displacement in the phase-field model", zh: "相场模型中的裂缝张开位移计算" },
              venue: { en: "Int. J. Solids and Structures", zh: "Int. J. Solids and Structures" },
              year: "2023", doi: "10.1016/j.ijsolstr.2023.112496", role: "co",
              contribution: { en: "Derives a unified line-integral form of crack opening for both brittle and cohesive phase-field models, validated on straight and curved cracks.", zh: "为脆性与内聚相场模型推导出统一的裂缝张开线积分表达式，并在直裂缝与曲裂缝上验证。" },
              img: "assets/papers/phasefield-crack-1.jpg",
              imgAlt: { en: "Phase field d and u·∇d for cracks inclined at 0°, 30°, 45°", zh: "倾角 0°、30°、45° 裂缝的相场 d 与 u·∇d 分布" } },
          ] },
        { title: { en: "Seismic & geotechnical engineering", zh: "地震与岩土工程" },
          image: null, motif: "seismic",
          meta: { en: "Collaborative · shaking-table tests · numerical simulation", zh: "合作研究 · 振动台试验 · 数值模拟" },
          blurb: { en: "Co-authored shaking-table and numerical studies (with C.L. Xin et al.) on the seismic stability of rock slopes and fault-crossing tunnels — covering near-fault pulse effects, dip/anti-dip benched slopes and ensemble-ML resilience prediction.", zh: "与 C.L. Xin 等合作开展的振动台试验与数值模拟研究，聚焦岩质边坡与跨断层隧道的地震稳定性，涵盖近断层脉冲效应、顺倾/反倾台阶边坡以及集成学习韧性预测。" },
          details: { highlights: [
            { en: "Combined large-scale shaking-table tests with numerical simulation (UDEC / FLAC3D) to validate slope and tunnel seismic stability.", zh: "将大型振动台试验与数值模拟（UDEC / FLAC3D）相结合，验证边坡与隧道的地震稳定性。" },
            { en: "Quantified near-fault pulse-like and fault-crossing effects on slopes, tunnels and fault containers.", zh: "量化近断层脉冲型地震动与跨断层效应对边坡、隧道及断层容器的影响。" },
            { en: "Built ensemble-ML surrogates for fast seismic-resilience prediction of fault-crossing tunnels.", zh: "构建集成学习代理模型，快速预测跨断层隧道的地震韧性。" },
          ] },
          tags: [{ tone: "slate", label: { en: "Shaking table", zh: "振动台" } }, { tone: "sage", label: { en: "Rock slopes", zh: "岩质边坡" } }, { tone: "kraft", label: { en: "Tunnels", zh: "隧道" } }, { tone: "heather", label: "ML" }],
          links: [],
          papers: [
            { emoji: "🛡️",
              title: { en: "Tunnel buffer layers under mainshock-aftershock sequences", zh: "主余震序列下的隧道缓冲层" },
              venue: { en: "Tunnelling & Underground Space Tech. · 2026", zh: "Tunnelling & Underground Space Tech. · 2026" },
              year: "2026", doi: "10.1016/j.tust.2026.107874", role: "co",
              contribution: { en: "Reveals how buffer-layer linings enhance tunnel performance and cut seismic damage under repeated mainshock-aftershock shaking.", zh: "揭示在主余震反复作用下，缓冲层衬砌如何提升隧道性能、减轻地震损伤。" } },
            { emoji: "⛰️",
              title: { en: "Rock Slopes under Near-Fault Pulse-Like Ground Motions", zh: "近断层脉冲型地震动下的岩质边坡" },
              venue: { en: "Rock Mechanics and Rock Engineering · 2025", zh: "Rock Mechanics and Rock Engineering · 2025" },
              year: "2025", doi: "10.1007/s00603-025-04798-w", role: "co",
              contribution: { en: "Shaking-table tests show pulse-like motions amplify slope Arias intensity up to 397% versus non-pulse shaking.", zh: "振动台试验表明，相比非脉冲地震动，脉冲型地震动使边坡 Arias 强度放大达 397%。" },
              metric: { en: "+397% Arias intensity", zh: "Arias 强度 +397%" },
              img: "assets/papers/rockslope-nearfault-1.jpg",
              imgAlt: { en: "Shaking-table experimental setup: stepped rock-slope model, sensor layout, and pulse-like seismic input scheme", zh: "振动台试验装置：台阶状岩质边坡模型、传感器布置与脉冲型地震动输入方案" } },
            { emoji: "🏗️",
              title: { en: "Strike-Slip Active Fault Container for Shaking Table Tests", zh: "振动台试验用走滑活动断层容器设计" },
              venue: { en: "J. Rock Mech. Geotech. Eng.", zh: "J. Rock Mech. Geotech. Eng." },
              year: "2025", doi: "10.1016/j.jrmge.2025.03.001", role: "co",
              contribution: { en: "Designed a fault container with adjustable angles; 23.74 Hz vs 6.355 Hz soil frequency (>2x) prevents resonance.", zh: "设计角度可调的断层容器，其 23.74 Hz 频率较土体 6.355 Hz 相差逾 2 倍，有效避免共振。" },
              metric: { en: "23.74 Hz vs 6.355 Hz", zh: "23.74 Hz vs 6.355 Hz" },
              img: "assets/papers/fault-container-1.jpg",
              imgAlt: { en: "3D schematic and physical model of the strike-slip fault container", zh: "走滑断层容器的三维示意图与实物模型" } },
            { emoji: "⛰️",
              title: { en: "Seismic Deformation & Failure of Anti-dip Bench Rock Slopes", zh: "反倾台阶岩质边坡的地震变形与破坏" },
              venue: { en: "Rock Mechanics and Rock Engineering · 2025", zh: "Rock Mechanics and Rock Engineering · 2025" },
              year: "2025", doi: "10.1007/s00603-024-04346-y", role: "co",
              contribution: { en: "Introduced the Displacement Baseline Offset Ratio (DBOR); crest displacement amplified up to 10.25x under seismic shaking.", zh: "提出位移基线偏移比（DBOR）；地震作用下坡顶位移最高放大 10.25 倍。" },
              metric: { en: "10.25x crest amplification", zh: "坡顶位移放大 10.25 倍" },
              img: "assets/papers/antidip-bench-slope-1.jpg",
              imgAlt: { en: "3D schematic and sensor layout of the discontinuous anti-dip bench rock slope model", zh: "不连续反倾台阶岩质边坡模型的三维示意图与传感器布置" } },
            { emoji: "🚄",
              title: { en: "Seismic resilience of fault-crossing HSR tunnels via ensemble learning", zh: "基于集成学习的跨断层高铁隧道抗震韧性分析" },
              venue: { en: "Underground Space · 2025", zh: "Underground Space · 2025" },
              year: "2025", doi: "10.1016/j.undsp.2025.04.011", role: "co",
              contribution: { en: "An Adaboost.RT surrogate replaces slow time-history analysis, predicting tunnel seismic damage at R2 = 0.96.", zh: "用 AdaBoost.RT 代理模型替代耗时的时程分析，隧道震损预测 R2 达 0.96。" },
              metric: { en: "R2 = 0.96", zh: "R2 = 0.96" },
              img: "assets/papers/tunnel-resilience-ml-1.jpg",
              imgAlt: { en: "Seismic resilience evaluation framework: Adaboost.RT surrogate, fragility curves, and restoration/resilience analysis", zh: "抗震韧性评估框架：AdaBoost.RT 代理模型、易损性曲线与恢复/韧性分析" } },
            { emoji: "🏔️",
              title: { en: "Seismic stability of benched bedding rock slopes", zh: "台阶式顺层岩质边坡的地震稳定性评价" },
              venue: { en: "Engineering Geology", zh: "Engineering Geology" },
              year: "2025", doi: "10.1016/j.enggeo.2025.108216", role: "co",
              contribution: { en: "Shaking-table tests and simulations yield a new dynamic stability index Sqt grading benched-slope seismic safety into four levels.", zh: "结合振动台试验与数值模拟，提出动态稳定性指标 Sqt，将台阶边坡的地震稳定性划分为四级。" },
              metric: { en: "4 stability levels", zh: "4 个稳定等级" },
              img: "assets/papers/benched-slope-landform-1.jpg",
              imgAlt: { en: "Progressive seismic failure of benched rock slopes: crack diagrams with shaking-table photos", zh: "台阶岩质边坡的渐进地震破坏：裂缝示意图与振动台试验照片" } },
            { emoji: "🏔️",
              title: { en: "Seismic shattering of bedding-parallel stepped rock slopes", zh: "顺层台阶状岩质边坡的地震震裂效应" },
              venue: { en: "J. Rock Mech. Geotech. Eng.", zh: "J. Rock Mech. Geotech. Eng." },
              year: "2024", doi: "10.1016/j.jrmge.2024.03.031", role: "co",
              contribution: { en: "Shaking-table tests plus FLAC3D reveal four shattering stages, pinpointing internal berm corners as the most vulnerable.", zh: "振动台试验结合 FLAC3D，揭示出四个震裂阶段，并指出台阶内角是最易破坏的部位。" },
              metric: { en: "4 failure stages", zh: "4 个破坏阶段" },
              img: "assets/papers/stepped-slope-shatter-1.jpg",
              imgAlt: { en: "Four-stage progressive failure of the stepped rock slope: schematics, model-test photos, and a deformation-vs-failure curve", zh: "台阶状岩质边坡的四阶段渐进破坏：示意图、模型试验照片与变形-破坏曲线" } },
            { emoji: "⛰️",
              title: { en: "Shaking-table tests on dip vs anti-dip rock slope stability", zh: "顺倾与反倾岩质边坡稳定性的振动台试验" },
              venue: { en: "Engineering Geology · 2024", zh: "Engineering Geology · 2024" },
              year: "2024", doi: "10.1016/j.enggeo.2024.107707", role: "co",
              contribution: { en: "Shaking-table tests show anti-dip slopes outperform dip slopes, pinpointing 0.6 g as the critical failure threshold.", zh: "振动台试验表明反倾边坡比顺倾边坡更稳定，并确定 0.6 g 为严重破坏的临界阈值。" },
              metric: { en: "0.6 g threshold", zh: "0.6 g 临界阈值" },
              img: "assets/papers/dip-antidip-slope-1.jpg",
              imgAlt: { en: "Sensor monitoring layout for dip (35deg) and anti-dip (16deg) benched rock slope models", zh: "顺倾(35度)与反倾(16度)台阶状岩质边坡模型的传感器监测布置" } },
            { emoji: "🚇",
              title: { en: "Casing-Shape Composite Tunnel Lining", zh: "套管型复合隧道衬砌" },
              venue: { en: "Soil Dynamics & Earthquake Engineering", zh: "Soil Dynamics & Earthquake Engineering" },
              year: "2022", doi: "10.1016/j.soildyn.2022.107440", role: "co",
              contribution: { en: "Buffer-layer composite lining diverts seismic forces to the outer shell, shielding the inner tunnel lining across fault slip.", zh: "缓冲层复合衬砌将地震内力转移到外衬砌，在断层滑移时保护内衬砌。" },
              img: "assets/papers/casing-tunnel-lining-1.jpg",
              imgAlt: { en: "Casing-shape composite lining concept and Timoshenko beam model", zh: "套管型复合衬砌概念与 Timoshenko 梁力学模型" } },
          ] },
      ],
    },
    {
      num: "PART 2",
      title:  { en: "National Highways & TRL", zh: "英国国家公路局 & 英国交通研究实验室" },
      period: "2020 – present",
      roles: [
        { en: "Senior Asset Data & Intelligence Analyst — National Highways", zh: "高级资产数据与智能分析师 — 英国国家公路局" },
        { en: "Researcher — Transport Research Laboratory (TRL)",             zh: "研究员 — 英国交通研究实验室 (TRL)" },
      ],
      blurb: { en: "Infrastructure data governance and transport AI at national scale.", zh: "国家级的基础设施数据治理与交通人工智能。" },
      projects: [
        { title: { en: "Unpaved Road Condition Analysis", zh: "未铺装路网 AI 评估" },
          image: null, motif: "multimodal",
          imageAlt: { en: "Multimodal machine-learning architecture diagram", zh: "多模态机器学习网络架构图" },
          meta: { en: "TRL · Python · multimodal ML", zh: "TRL · Python · 多模态机器学习" },
          blurb: { en: "Assessing unpaved roads from satellite imagery with multimodal ML and a fine-tuned LLaVA vision-language model — cut survey cost to €22/km, deployed in Tanzania & Madagascar. Best Paper, ITS Asia-Pacific.", zh: "用多模态机器学习与微调的 LLaVA 视觉语言模型，从卫星影像评估未铺装道路，将调查成本降到约 €22/km，并在坦桑尼亚与马达加斯加落地；获 ITS 亚太会议最佳论文奖。" },
          details: { highlights: [
            { en: "Fused satellite imagery, road sensors and a fine-tuned LLaVA vision-language model into one multimodal classifier.", zh: "将卫星影像、道路传感器与微调的 LLaVA 视觉语言模型，融合为统一的多模态分类器。" },
            { en: "Cut field-survey cost to about €22/km, making national-scale assessment viable.", zh: "把实地调查成本降到约 €22/km，让国家级评估变得可行。" },
            { en: "Deployed across road networks in Tanzania & Madagascar; won Best Paper at ITS Asia-Pacific.", zh: "在坦桑尼亚与马达加斯加路网落地，并获 ITS 亚太会议最佳论文奖。" },
          ] },
          tags: [{ tone: "kraft", label: "Python" }, { tone: "heather", label: { en: "Deep learning", zh: "深度学习" } }, { tone: "slate", label: { en: "Remote sensing", zh: "遥感" } }],
          links: [{ label: "GitHub", href: "https://github.com/wangzhao0217/satellite-unpaved-roads", icon: "github" }, { label: "DOI", href: "https://doi.org/10.1016/j.jtrangeo.2025.104525", icon: "link-45deg" }],
          papers: [
            { emoji: "🛰️",
              title: { en: "Unpaved road assessment in Africa via multimodal ML and vision-language models", zh: "用多模态机器学习与视觉-语言模型评估非洲未铺装道路" },
              venue: { en: "J. Transport Geography", zh: "J. Transport Geography" },
              year: "2026", doi: "10.1016/j.jtrangeo.2025.104525", role: "first",
              contribution: { en: "Multimodal ML hits 93.2% road-condition accuracy and holds 84–85% on cheaper low-resolution satellite imagery via transfer learning.", zh: "多模态机器学习的路况识别准确率达 93.2%，借助迁移学习在更廉价的低分辨率卫星影像上仍保持 84–85%。" },
              metric: { en: "93.2% accuracy", zh: "93.2% 准确率" },
              img: "assets/papers/unpaved-africa-1.jpg",
              imgAlt: { en: "Multimodal ML architecture fusing CNN, ResNet50V2 and handcrafted features for road-condition prediction", zh: "融合 CNN、ResNet50V2 与手工特征的多模态机器学习架构图，用于路况预测" } },
            { emoji: "🛰️",
              title: { en: "Predicting Unpaved Road Conditions from Satellite Imagery", zh: "用卫星影像预测未铺装道路状况" },
              venue: { en: "Remote Sensing (MDPI)", zh: "Remote Sensing (MDPI)" },
              year: "2023", doi: "10.3390/rs15163985", role: "co",
              contribution: { en: "Classifies rural unpaved road condition from satellite pixel variation, with a blended ML classifier reaching 88% accuracy.", zh: "依据卫星像素变化对乡村未铺装道路状况分类，混合机器学习分类器准确率达 88%。" },
              metric: { en: "88% accuracy", zh: "88% 准确率" },
              img: "assets/papers/unpaved-prediction-1.jpg",
              imgAlt: { en: "Satellite crops of unpaved roads in good, fair, poor and bad condition", zh: "良好、一般、较差、很差四种状况下未铺装道路的卫星影像切片" } },
            { emoji: "🏆",
              title: { en: "Assessment of unpaved road network using satellite imagery and machine learning", zh: "基于卫星影像与机器学习的未铺装路网评估" },
              venue: { en: "ITS Asia-Pacific, Chengdu — Best Paper", zh: "智能交通系统亚太会议，成都 — 最佳论文奖" },
              year: "2022", role: "first",
              contribution: { en: "Best Paper award: first demonstration that satellite imagery plus machine learning can assess national unpaved-road condition.", zh: "最佳论文奖：首次证明卫星影像加机器学习可用于国家级未铺装路网状况评估。" } },
          ] },
        { title: { en: "National asset data alignment: GDMS ⇄ Confirm", zh: "国家级资产数据空间对齐：GDMS ⇄ Confirm" },
          image: null, motif: "align",
          meta: { en: "National Highways · Python · ArcPy", zh: "英国国家公路局 · Python · ArcPy" },
          blurb: { en: "Rebuilt the spatial-matching engine in Python/ArcPy to reconcile two national drainage-asset datasets across the Strategic Road Network — cut data deviation by 99% and manual review by 85%, now deployed nationwide.", zh: "用 Python/ArcPy 重写空间比对引擎，打通国家战略路网两大排水资产数据库，使数据偏差降低 99%、人工复审减少 85%，现已在全国推广。" },
          details: { highlights: [
            { en: "Rebuilt the spatial-matching engine in Python/ArcPy to reconcile GDMS and Confirm drainage datasets.", zh: "用 Python/ArcPy 重写空间比对引擎，打通 GDMS 与 Confirm 两套排水资产数据库。" },
            { en: "Reduced data deviation by 99% and manual review effort by 85%.", zh: "数据偏差降低 99%，人工复审工作量减少 85%。" },
            { en: "Now deployed nationwide across the Strategic Road Network.", zh: "已在国家战略路网（SRN）全国落地。" },
          ] },
          tags: [{ tone: "slate", label: "ArcGIS Pro" }, { tone: "kraft", label: "Python" }, { tone: "sage", label: { en: "ETL", zh: "数据管线" } }],
          links: [] },
        { title: { en: "Road safety & flood-risk intelligence", zh: "道路安全与洪涝风险智能分析" },
          image: null, motif: "floodgis",
          imageAlt: { en: "Flood-event image checker beside a road-asset map", zh: "洪涝事件图像核查工具与路网资产地图" },
          meta: { en: "TRL / National Highways · ML · GIS", zh: "TRL / 国家公路局 · 机器学习 · GIS" },
          blurb: { en: "Skid-resistance forecasting from climate data; a collision-risk model for Ireland's roads; PointCNN LiDAR asset extraction; and STATS19 collision clustering to prioritise the Road Liable to Flooding programme.", zh: "用气候数据预测路面抗滑性、为爱尔兰道路建立碰撞预测模型、用 PointCNN 从激光雷达点云提取资产，并通过 STATS19 碰撞聚类为易涝路段排定治理优先级。" },
          details: { highlights: [
            { en: "Forecast skid-resistance from climate data and built a collision-risk model for Ireland's roads.", zh: "用气候数据预测路面抗滑性，并为爱尔兰道路建立碰撞预测模型。" },
            { en: "Extracted road assets from LiDAR point clouds with PointCNN.", zh: "用 PointCNN 从激光雷达点云中提取道路资产。" },
            { en: "Clustered STATS19 collisions to prioritise the Road Liable to Flooding programme.", zh: "对 STATS19 碰撞数据聚类，为易涝道路治理计划排定优先级。" },
          ] },
          tags: [{ tone: "heather", label: { en: "ML", zh: "机器学习" } }, { tone: "slate", label: { en: "LiDAR", zh: "激光雷达" } }, { tone: "clay", label: { en: "Flood risk", zh: "洪涝风险" } }],
          links: [] },
      ],
    },
    {
      num: "PART 3",
      title:  { en: "University of Leeds — ITS", zh: "英国利兹大学 · 交通研究所" },
      period: "2023 – present",
      roles: [
        { en: "Research Fellow — Institute for Transport Studies (Horizon Europe)", zh: "研究员 — 交通研究所（欧盟 Horizon Europe 项目）" },
      ],
      blurb: { en: "National transport-network modelling and high-performance open-source GIS.", zh: "国家级交通网络建模与高性能开源 GIS。" },
      projects: [
        { title: { en: "Network Planning Tool for Scotland", zh: "苏格兰国家自行车路网规划平台 (NPT)" },
          image: null, motif: "nptmap",
          imageAlt: { en: "Cycle route network coloured by flow, Edinburgh", zh: "爱丁堡自行车路网按流量着色" },
          meta: { en: "Lead developer · R · live tool", zh: "主要开发者 · R · 在线平台" },
          blurb: { en: "A national, open cycle-network planning tool used by all 32 Scottish local authorities to estimate cycle uptake and prioritise investment (NPT & NPW).", zh: "面向全国的开源自行车路网规划平台（NPT 与 NPW），苏格兰全部 32 个地方政府都在用它估算骑行需求、辅助投资决策。" },
          details: { highlights: [
            { en: "Lead developer of the open Network Planning Tool used by all 32 Scottish local authorities.", zh: "开源苏格兰路网规划平台主要开发者，已被全部 32 个地方政府采用。" },
            { en: "Estimates cycling uptake and prioritises investment from open origin–destination data.", zh: "基于开放的起讫点（OD）数据估算骑行需求，并优选投资方向。" },
            { en: "Renders interactive route networks coloured by projected flow.", zh: "按预测流量着色，交互式呈现整张路网。" },
          ] },
          tags: [{ tone: "slate", label: "R" }, { tone: "sage", label: { en: "Route networks", zh: "路网" } }],
          links: [{ label: "GitHub", href: "https://github.com/nptscot/npt", icon: "github" }, { label: { en: "Live tool", zh: "在线平台" }, href: "https://nptscot.github.io", icon: "box-arrow-up-right" }] },
        { title: { en: "stplanr", zh: "stplanr" },
          image: null, motif: "desire",
          imageAlt: { en: "Origin–destination desire lines across a region", zh: "区域起讫点（OD）期望线" },
          meta: { en: "Contributor · R · 50,000+ downloads", zh: "贡献者 · R · 下载量 5 万+" },
          blurb: { en: "Sustainable transport planning with R: desire lines, routing and travel-flow aggregation. An rOpenSci package in production use by UK government transport agencies.", zh: "面向可持续交通规划的 R 软件包：期望线、路径计算与出行流量聚合。rOpenSci 旗下项目，已被英国政府交通机构投入实际使用。" },
          details: { highlights: [
            { en: "Core contributor to the rOpenSci stplanr package (50,000+ downloads).", zh: "rOpenSci stplanr 软件包核心贡献者（下载量 5 万+）。" },
            { en: "Provides desire lines, routing and travel-flow aggregation for transport planning.", zh: "为交通规划提供期望线、路径计算与出行流量聚合。" },
            { en: "In production use by UK government transport agencies.", zh: "已被英国政府交通机构投入生产使用。" },
          ] },
          tags: [{ tone: "slate", label: "R" }, { tone: "heather", label: "rOpenSci" }],
          links: [{ label: "GitHub", href: "https://github.com/ropensci/stplanr", icon: "github" }, { label: "DOI", href: "https://doi.org/10.32614/RJ-2018-053", icon: "link-45deg" }] },
        { title: { en: "corenet", zh: "corenet" },
          image: null, motif: "corenet",
          meta: { en: "First author · R · J. Transport Geography 2026", zh: "第一作者 · R · J. Transport Geography 2026" },
          blurb: { en: "A flexible framework for generating and prioritising 'core' cycle network designs, combining diverse datasets with user requirements — used by Transport Scotland and DfT.", zh: "一套灵活的框架，融合多源数据与用户需求，生成并优选「核心」自行车路网方案，已被苏格兰交通局与英国交通部采用。" },
          details: { highlights: [
            { en: "First-author framework that generates and prioritises 'core' cycle network designs.", zh: "以第一作者开发的框架，生成并优选「核心」自行车路网方案。" },
            { en: "Combines diverse open datasets with planner requirements and constraints.", zh: "将多源开放数据与规划者的需求和约束结合起来。" },
            { en: "Used by Transport Scotland and DfT; published in J. Transport Geography (2026).", zh: "已被苏格兰交通局与英国交通部采用，相关成果发表于 J. Transport Geography（2026）。" },
          ] },
          tags: [{ tone: "slate", label: "R" }, { tone: "sage", label: { en: "Networks", zh: "路网" } }, { tone: "clay", label: { en: "Optimisation", zh: "优化" } }],
          links: [{ label: "GitHub", href: "https://github.com/nptscot/corenet", icon: "github" }, { label: "DOI", href: "https://doi.org/10.1016/j.jtrangeo.2025.104549", icon: "link-45deg" }],
          papers: [
            { emoji: "🚲",
              title: { en: "Corenet: Generating & Prioritising Core Cycle Networks", zh: "Corenet：生成并优选核心自行车路网" },
              venue: { en: "J. Transport Geography", zh: "J. Transport Geography" },
              year: "2026", doi: "10.1016/j.jtrangeo.2025.104549", role: "first",
              contribution: { en: "An open-source method that builds cohesive cycle networks, lifting routing efficiency up to 188x over fragmented existing infrastructure.", zh: "开源方法生成连贯成网的核心自行车路网，路由效率较现有零散基础设施最高提升 188 倍。" },
              metric: { en: "up to 188x efficiency", zh: "效率最高提升 188 倍" },
              img: "assets/papers/corenet-1.jpg",
              imgAlt: { en: "Generated core cycle networks (red) vs. fragmented existing infrastructure (blue) across four Scottish cities", zh: "四个苏格兰城市：生成的核心自行车路网（红）与零散的现有基础设施（蓝）对比" } },
          ] },
        { title: { en: "parenx — network simplification", zh: "parenx — 路网简化" },
          image: null, motif: "simplify",
          meta: { en: "Python · open source", zh: "Python · 开源" },
          blurb: { en: "A Python package that simplifies complex street networks using buffer/Voronoi and image-skeletonisation methods — turning tangled road geometry into clean, analysis-ready centrelines.", zh: "一个 Python 软件包，用缓冲区/Voronoi 与图像骨架化方法简化复杂的街道路网，把杂乱的道路几何整理成干净、可直接分析的中心线。" },
          details: { highlights: [
            { en: "Simplifies dense road geometry via skeletonisation and buffer/Voronoi methods.", zh: "用骨架化与缓冲区/Voronoi 方法简化密集的道路几何。" },
            { en: "Produces clean, analysis-ready centrelines for network modelling.", zh: "输出干净、可直接用于网络建模的中心线。" },
            { en: "Open-source Python package by anisotropi4, used in active-travel pipelines.", zh: "由 anisotropi4 开发的开源 Python 软件包，已用于主动出行数据管线。" },
          ] },
          tags: [{ tone: "kraft", label: "Python" }, { tone: "sage", label: { en: "Networks", zh: "路网" } }],
          links: [{ label: "GitHub", href: "https://github.com/anisotropi4/parenx", icon: "github" }, { label: "PyPI", href: "https://pypi.org/project/parenx/", icon: "box-arrow-up-right" }],
          papers: [
            { emoji: "🛣️",
              title: { en: "Route network simplification for transport planning", zh: "面向交通规划的路网简化" },
              venue: { en: "Environ. Plan. B: Urban Analytics · 2025", zh: "Environ. Plan. B: Urban Analytics · 2025" },
              year: "2025", doi: "10.1177/23998083251387986", role: "co",
              contribution: { en: "Two open-source methods, skeletonization and Voronoi centrelines, collapse braided road networks into clean single corridors.", zh: "用骨架化与 Voronoi 中心线两种开源方法，把交织缠绕的路网合并成整洁的单一廊道。" },
              img: "assets/papers/route-simplification-1.jpg",
              imgAlt: { en: "Edinburgh road network simplified by skeletonization, Voronoi and primal methods", zh: "爱丁堡路网经骨架化、Voronoi 与原始法简化后的对比" } },
          ] },
        { title: { en: "anime — network matching", zh: "anime — 路网匹配" },
          image: null, motif: "match",
          meta: { en: "Rust · R · with Esri", zh: "Rust · R · 与 Esri 合作" },
          blurb: { en: "Approximate Network Integration, Matching & Enrichment — a Rust-accelerated engine with R bindings (built with Esri engineers) that matches features between road networks, delivering up to 1000× speed-ups on large-scale spatial computation.", zh: "Approximate Network Integration, Matching & Enrichment：用 Rust 加速、带 R 接口的引擎（与 Esri 工程师合作开发），在不同路网之间匹配要素，大规模空间计算最高提速 1000 倍。" },
          details: { highlights: [
            { en: "Matches and transfers attributes between two road networks (integration & enrichment).", zh: "在两个路网之间匹配要素并迁移属性（集成与增强）。" },
            { en: "Rust core with R bindings, developed together with Esri engineers.", zh: "Rust 内核搭配 R 接口，与 Esri 工程师共同开发。" },
            { en: "Delivers up to 1000× speed-ups on large-scale spatial computation.", zh: "在大规模空间计算中最高提速 1000 倍。" },
          ] },
          tags: [{ tone: "heather", label: "Rust" }, { tone: "slate", label: "R" }],
          links: [{ label: "GitHub", href: "https://github.com/JosiahParry/anime", icon: "github" }] },
        { title: { en: "Horizon Europe — ZEV-UP · ePowerMove · WibiCharge", zh: "欧盟 Horizon Europe — ZEV-UP · ePowerMove · WibiCharge" },
          image: null, motif: "ev",
          meta: { en: "Lead researcher (Leeds) · EV systems", zh: "利兹大学项目负责人 · 电动车系统" },
          blurb: { en: "Leading Leeds' work on EU EV projects: feasibility & life-cycle assessment for frugal EVs (ZEV-UP), smart-charging network planning (ePowerMove) and wireless-charging infrastructure siting (WibiCharge).", zh: "牵头利兹大学在欧盟电动车项目中的工作：低成本电动车的可行性与全生命周期评估（ZEV-UP）、智能充电网络规划（ePowerMove），以及无线充电基础设施选址（WibiCharge）。" },
          details: { highlights: [
            { en: "Leads Leeds' work across three EU Horizon Europe electric-vehicle projects.", zh: "牵头利兹大学在三个欧盟 Horizon Europe 电动车项目中的工作。" },
            { en: "Feasibility & life-cycle assessment for frugal EVs (ZEV-UP).", zh: "低成本电动车的可行性与全生命周期评估（ZEV-UP）。" },
            { en: "Smart-charging network planning (ePowerMove) and wireless-charging siting (WibiCharge).", zh: "智能充电网络规划（ePowerMove）与无线充电选址（WibiCharge）。" },
          ] },
          tags: [{ tone: "sage", label: { en: "EV", zh: "电动车" } }, { tone: "slate", label: { en: "Optimisation", zh: "优化" } }],
          links: [] },
      ],
    },
  ],

  education: [
    { degree: { en: "Ph.D., Civil & Structural Engineering", zh: "土木与结构工程 博士" }, school: { en: "University of Sheffield", zh: "英国谢菲尔德大学" }, year: "2015 – 2019" },
    { degree: { en: "MSc, Civil Engineering (Distinction)", zh: "土木工程 硕士（优异）" }, school: { en: "Cardiff University", zh: "英国卡迪夫大学" }, year: "2013 – 2014" },
    { degree: { en: "BSc, Civil Engineering", zh: "土木工程 学士" }, school: { en: "Shijiazhuang Railway University", zh: "石家庄铁道大学" }, year: "2008 – 2012" },
  ],

  talk: {
    title: { en: "Assessment of Unpaved Road Networks using Satellite Imagery & Machine Learning", zh: "基于卫星影像与机器学习的未铺装路网评估" },
    venue: { en: "Intelligent Transport Systems Asia-Pacific, Chengdu — Best Paper Award", zh: "智能交通系统亚太会议，成都 — 最佳论文奖" },
    poster: "assets/unpaved-roads-ml.jpg",
    youtubeId: "", // ← set your own talk/demo recording id
    note: { en: "Drop in your own talk or demo recording — set talk.youtubeId in site-data.js.", zh: "在 site-data.js 中设置 talk.youtubeId，即可嵌入自己的演讲或演示录像。" },
  },

  // Academic titles/venues stay in English (papers are published in English).
  publications: [
    { year: "2026", type: "Journal", authors: "Hu, Y., Xin, C.L., Wang, Z., Yu, X.Y., Feng, W.K., Hajirasouliha, I.", title: "Dynamic response and performance enhancement mechanisms of tunnel buffer layers under mainshock-aftershock sequences", venue: "Tunnelling and Underground Space Technology, 176, 107874", doi: "10.1016/j.tust.2026.107874" },
    { year: "2026", type: "Journal", authors: "Wang, Z., Hu, H., Mahfouz, H., Fonseca-Zamora, J.P., Lucas-Smith, M., Carlino, D., Calder, A., Hu, C., Davis, M., Talbot, J., Lovelace, R.", title: "Corenet: a flexible framework for generating and prioritising core cycle network designs", venue: "Journal of Transport Geography, 131, 104549", doi: "10.1016/j.jtrangeo.2025.104549" },
    { year: "2026", type: "Journal", authors: "Wang, Z., Xin, C., Workman, R., Hu, H., Yu, X., Tian, Y., Lovelace, R., Zhang, J., Chen, H.", title: "Advancing unpaved road assessment in Africa: leveraging multimodal machine learning and large language-and-vision assistants across satellite imagery resolutions", venue: "Journal of Transport Geography, 131, 104525", doi: "10.1016/j.jtrangeo.2025.104525" },
    { year: "2025", type: "Journal", authors: "Deakin, W., Wang, Z., Parry, J., Lovelace, R.", title: "Route network simplification for transport planning", venue: "Environment and Planning B: Urban Analytics and City Science", doi: "10.1177/23998083251387986" },
    { year: "2025", type: "Conference", authors: "Lovelace, R., Wang, Z., Mahfouz, H.", title: "Mapping, classifying, and integrating diverse street network datasets: new methods and open source tools for active travel planning", venue: "33rd GIS Research UK Conference (GISRUK), Bristol, UK" },
    { year: "2025", type: "Journal", authors: "Feng, W.K., Xin, C.L., Wang, Z., Yu, X.Y.", title: "Design of a type of strike-slip active fault container for shaking table tests", venue: "Journal of Rock Mechanics and Geotechnical Engineering", doi: "10.1016/j.jrmge.2025.03.001" },
    { year: "2025", type: "Journal", authors: "Fei, Y., Xin, C.L., Wang, Z., Yu, X.Y., Feng, W.K., Hu, Y.", title: "Investigating deformation and failure mechanisms of discontinuous anti-dip bench rock slopes through shaking table tests and numerical simulations", venue: "Rock Mechanics and Rock Engineering, 58, 5329–5361", doi: "10.1007/s00603-024-04346-y" },
    { year: "2025", type: "Journal", authors: "Xin, C.L., Zeng, L., Wang, Z., Feng, W.K., Yu, X., Hajirasouliha, I.", title: "Characterizing dynamic responses of rock slopes to near-fault pulse-like ground motions: insights from shaking table tests and numerical analysis", venue: "Rock Mechanics and Rock Engineering", doi: "10.1007/s00603-025-04798-w" },
    { year: "2025", type: "Journal", authors: "Xin, C.L., Li, W.H., Wang, Z., Feng, W.K., Yu, X., Hajirasouliha, I.", title: "Seismic stability evaluation of benched bedding rock slopes with varying landforms", venue: "Engineering Geology, 344, 108216", doi: "10.1016/j.enggeo.2025.108216" },
    { year: "2025", type: "Journal", authors: "Xin, C.L., Yang, L.J., Wang, Z., Yu, X., Feng, W.K.", title: "Seismic resilience analysis of high-speed railway tunnels across fault zones using ensemble learning approach", venue: "Underground Space", doi: "10.1016/j.undsp.2025.04.011" },
    { year: "2024", type: "Journal", authors: "Wang, Z., Hu, H., Papastergiou, P., Angelakopoulos, H., Guadagnini, M., Pilakoutas, K.", title: "Effect of fibre length on the mechanical properties of SFRC using recycled steel fibres", venue: "Construction and Building Materials, 415, 134890", doi: "10.1016/j.conbuildmat.2024.134890" },
    { year: "2024", type: "Journal", authors: "Xin, C.L., Fei, Y., Feng, W.K., Wang, Z., Li, W.H.", title: "Seismic responses and shattering cumulative effects of bedding parallel stepped rock slope: model test and numerical simulation", venue: "Journal of Rock Mechanics and Geotechnical Engineering", doi: "10.1016/j.jrmge.2024.03.031" },
    { year: "2024", type: "Journal", authors: "Xin, C.L., Li, W.H., Wang, Z., Feng, W.K., Hajirasouliha, I., Yu, X.Y.", title: "Shaking table tests on the stability of dip and anti-dip rock slopes with structural planes induced by seismic motions", venue: "Engineering Geology, 340, 107707", doi: "10.1016/j.enggeo.2024.107707" },
    { year: "2024", type: "Conference", authors: "Lovelace, R., Wang, Z., Deakin, W., Parry, J.", title: "Reproducible methods for network simplification for data visualisation and transport planning", venue: "32nd GIS Research UK Conference (GISRUK), Leeds, UK", doi: "10.5281/zenodo.11077553" },
    { year: "2023", type: "Journal", authors: "Workman, R., Wong, P., Wright, A., Wang, Z.", title: "Prediction of unpaved road conditions using high-resolution optical satellite imagery and machine learning", venue: "Remote Sensing, 15(16), 3985", doi: "10.3390/rs15163985" },
    { year: "2023", type: "Journal", authors: "Chen, L., Wang, Z., Li, B., de Borst, R.", title: "Computation of the crack opening displacement in the phase-field model", venue: "International Journal of Solids and Structures, 283, 112496", doi: "10.1016/j.ijsolstr.2023.112496" },
    { year: "2022", type: "Journal", authors: "Xin, C.L., Wang, Z., Hajirasouliha, I., Chen, T., Gao, B.", title: "Seismic response mechanisms of casing-shape composite tunnel lining: theoretical analysis and shaking table test verification", venue: "Soil Dynamics and Earthquake Engineering, 162, 107440", doi: "10.1016/j.soildyn.2022.107440" },
    { year: "2022", type: "Conference", authors: "Wang, Z., Workman, R.", title: "Assessment of unpaved road network using satellite imagery and machine learning", venue: "Intelligent Transport Systems Asia-Pacific, Chengdu, China", best: true },
    { year: "2020", type: "Journal", authors: "Wang, Z., Hajirasouliha, I., Guadagnini, M., Pilakoutas, K.", title: "Axial behaviour of FRP-confined concrete columns: an experimental investigation", venue: "Construction and Building Materials, 263, 121023", doi: "10.1016/j.conbuildmat.2020.121023" },
    { year: "2020", type: "Journal", authors: "Wang, Z., Hu, H., Guadagnini, M., Pilakoutas, K.", title: "Tensile stress-strain characteristics of rubberised concrete from flexural tests", venue: "Construction and Building Materials, 236, 117591", doi: "10.1016/j.conbuildmat.2019.117591" },
    { year: "2019", type: "Journal", authors: "Wang, Z., Chen, L., Guadagnini, M., Pilakoutas, K.", title: "Shear behaviour model for confined and unconfined rubberised concrete", venue: "Journal of Composites for Construction", doi: "10.1061/(ASCE)CC.1943-5614.0000962" },
    { year: "2018", type: "Journal", authors: "Hu, H., Wang, Z., Figueiredo, F.P., Papastergiou, P., Guadagnini, M., Pilakoutas, K.", title: "Post-cracking tensile behaviour of blended steel fibre reinforced concrete", venue: "Structural Concrete", doi: "10.1002/suco.201800100" },
    { year: "2017", type: "Conference", authors: "Wang, Z., Margarit, D.E., Guadagnini, M., Pilakoutas, K.", title: "Shear behaviour of confined and unconfined rubberised concrete", venue: "1st Int. Conf. on Construction Materials for Sustainable Future, Zadar, Croatia" },
    { year: "2017", type: "Conference", authors: "Margarit, D.E., Wang, Z., Guadagnini, M., Pilakoutas, K.", title: "Proof-of-concept testing of FRP confined rubberised concrete coupling beams", venue: "Advanced Composites in Construction (ACIC), Sheffield, UK" },
  ],
};
